name: Openwrt-cli

on:
  push:
    branches: 
      - openwrt-21.02
jobs:
  buid_openwrt:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: make
        run: |
          ls
          cd immortalwrt-mt798x
          ./scripts/feeds update -a 
          ./scripts/feeds install -a
          make
