name: Openwrt-cli

on:
  push:
    branches: 
      - openwrt-21.02
jobs:
  buid_openwrt:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: make
        run: |
          git https://github.com/happysun85/immortalwrt-mt798x.git
          sudo -E bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
          ls
          cd immortalwrt-mt798x
          ./scripts/feeds update -a 
          ./scripts/feeds install -a
          make
