name: Openwrt-cli

on:
  workflow_dispatch: 
jobs:
  build_openwrt:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download and run custom script
        run: |
          curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh -o init_build_environment.sh
          chmod +x init_build_environment.sh
        
