name: Openwrt-cli

on:
  push:
    branches: 
      - openwrt-21.02
jobs:
  build_openwrt:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
      - name: make
        run: |
          bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)
          ls
          ./scripts/feeds update -a 
          ./scripts/feeds install -a
          make -j$(nproc) V=s
